services:
  # Backend
  unen-backend-dev:
    container_name: unen-backend-dev
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - 32132:32132
    depends_on:
      - unen-database-dev
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://unen:unen@unen-database-dev/unen

  # Database
  unen-database-dev:
    container_name: unen-database-dev
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_PASSWORD: unen
      POSTGRES_USER: unen
      POSTGRES_DB: unen
    ports:
      - 5432:5432

  # Pgadmin
  unen-pgadmin-dev:
    container_name: unen-pgadmin-dev
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - unen-database-dev
