[package]
name = "unen_backend"
version.workspace = true
edition.workspace = true

################################################################################
# DEPENDENCIES
################################################################################
[dependencies.anyhow]
workspace = true
