[package]
name = "unen-engine"
version.workspace = true
edition.workspace = true
license = "AGPL-3.0"

################################################################################
# TESTING
################################################################################
[dev-dependencies.serial_test]
workspace = true

################################################################################
# ERROR
################################################################################
[dependencies.thiserror]
workspace = true

################################################################################
# LOGGING
################################################################################
[dependencies.log]
workspace = true

[dependencies.env_logger]
workspace = true

################################################################################
# CONCURRENCY
################################################################################
[dependencies.crossbeam]
workspace = true

################################################################################
# ALGORITHM
################################################################################
[dependencies.strum]
workspace = true

################################################################################
# RENDERING
################################################################################
[dependencies.winit]
workspace = true
